### ISSUE TITLE
build error: destination path '/tmp/.../maximal' already exists 

### ISSUE THREAD

**Issue by daudo** [memeplex/maximal#1]
[udo@veteris ~]$ yaourt -S maximal

```
==> Downloading maximal PKGBUILD from AUR...
[...]
==> Building and installing package
==> Making package: maximal 20180705-1 (Mi 12 Sep 2018 15:07:59 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning maximal git repo...
fatal: destination path '/tmp/yaourt-tmp-udo/aur-maximal/maximal' already exists and is not an empty directory.
==> ERROR: Failure while downloading maximal git repo
    Aborting...

```

**Comment by memeplex** [comment]
Could this be related to some recent change in makepkg behavior? My PKGBUILD is rather plain.

**Comment by crazygolem** [comment]
The [commit message](https://git.archlinux.org/pacman.git/commit/?id=793202344b47914d06a2c48bacbb6b232f7c5387) of a fix for a similar (but not identical) issue mentions:

> In some cases, this could result in makepkg erroring when trying to
> create $srcdir/$pkgdir, if a file with the same name as the $pkgbase
> exists.

The commit doesn't seem to address the present issue, but the comment hints to a potential solution: changing some names, e.g.: `source=("maximal-git::git+$url.git")` and then adapting the path in the `package` function.

**Comment by memeplex** [comment]
I have merged your PR, thanks!
